### Variáveis
@baseUrl = http://localhost:5090
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiItYnpfTi1jS05LeXIiLCJ1bmlxdWVfbmFtZSI6IkFkbWluaXN0cmF0b3IiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzQ5OTk1OTc4LCJleHAiOjE3NDk5OTk1NzgsImlhdCI6MTc0OTk5NTk3OCwiaXNzIjoiYXBpLS1kYXBwZXIiLCJhdWQiOiJhcGktLWRhcHBlci1jbGllbnRzIn0.E8G1ttdU6LhVVeU0oy0dtjSAqqFflExxbJ8yDxmDYL0
@userId = -bz_N-cKNKyr

### Get All Users (Admin only)
GET {{baseUrl}}/api/users
Authorization: Bearer {{token}}

### Get User by ID (User or Admin)
GET {{baseUrl}}/api/users/{{userId}}
Authorization: Bearer {{token}}

### Create User
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "name": "Pedro Costa",
  "email": "pedro@example.com",
  "password": "pedro123"
}

### Create User - teste com email duplicado
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "name": "Ana Lima",
  "email": "pedro@example.com",
  "password": "ana123"
}

### Update User (User or Admin)
PUT {{baseUrl}}/api/users/{{userId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Pedro Costa Silva",
  "email": "pedro.silva@example.com",
  "password": "newpassword123"
}

### Update User - sem alterar senha
PUT {{baseUrl}}/api/users/{{userId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Pedro Costa Silva",
  "email": "pedro.silva@example.com"
}

### Delete User (Admin only)
DELETE {{baseUrl}}/api/users/{{userId}}
Authorization: Bearer {{token}}

### Teste sem autenticação
GET {{baseUrl}}/api/users

### Teste com token inválido
GET {{baseUrl}}/api/users
Authorization: Bearer invalid-token-here
